### ISSUE TITLE
Crash on sim startup

### ISSUE THREAD

**Issue by byBlurr** [lespalt/iRon#22]
I installed iRacing on my laptop for testing my changes.

I am getting this crash when my sim finishes loading.
![image](https://github.com/lespalt/iRon/assets/20552533/9b8d5343-3155-47c2-8929-6d118245b321)

If I manage to close the app and reopen it, it just freezes with all overlays blanks.

I am not getting any logs, my visual studio is also crashing along with the app. I have checked out at the last commit committed before I contributed, so its not caused by my untested changes. Is anyone else having this issue? It may be the laptop, iRacing is crazy laggy on it.

I will checkout at an even earlier commit to test.

**Comment by frmjar** [comment]
You need to comment out line 297 in irsdk_client.cpp
![image](https://github.com/lespalt/iRon/assets/16623932/3150d00a-924f-4147-87c6-f207567a2241)

**Comment by byBlurr** [comment]
> You need to comment out line 297 in irsdk_client.cpp ![image](https://user-images.githubusercontent.com/16623932/262681556-3150d00a-924f-4147-87c6-f207567a2241.png)

Ahh, I checked if variables were valid. Fix from here: #14
